#!/usr/bin/env bash
# source this file to add dependencies to C_INCLUDE_PATH environment variable

abs=$(readlink -f $(dirname "$0"))
includes=($abs/glad $abs/glfw)

for incl in ${includes[@]}; do
    if [[ "$C_INCLUDE_PATH" != *"$incl"* ]]; then
        export C_INCLUDE_PATH=$C_INCLUDE_PATH:$incl
    fi
done
